actions:
  pre:
    vundle-install: test -e ~/.vim/bundle/Vundle.vim || (mkdir -p ~/.vim/bundle; git
      clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim)
    tpm-install: test -e ~/.tmux/plugins/tpm/.git || git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
    oh-my-zsh-install: test -e ~/.oh-my-zsh/.git || sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh
      | sed '/exec zsh/d')"
    p10k-install: test -e ~/.oh-my-zsh/custom/themes/powerlevel10k/.git || git clone
      --depth=1 https://github.com/romkatv/powerlevel10k.git ~/.oh-my-zsh/custom/themes/powerlevel10k
  vundle: vim +VundleClean! +VundleInstall +VundleInstall! +qall
config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  f_vimrc:
    src: vimrc
    dst: ~/.vimrc
    link: link
    actions:
    - vundle-install
    - vundle
  f_tmux.conf:
    src: tmux.conf
    dst: ~/.tmux.conf
    link: link
    actions:
    - tpm-install
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
    link: link
    actions:
    - oh-my-zsh-install
    - p10k-install
  f_aliases:
    src: aliases
    dst: ~/.aliases
    link: link
  f_condarc:
    src: condarc
    dst: ~/.condarc
    link: link
  f_p10k.zsh:
    src: p10k.zsh
    dst: ~/.p10k.zsh
profiles:
  Joshuas-MacBook-Pro.local:
    dotfiles:
    - f_vimrc
    - f_tmux.conf
    - f_zshrc
    - f_aliases
    - f_condarc
    - f_p10k.zsh
